@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as PLAYER
participant ":ViewStationDetailsUI" as UI
participant ":ViewStationDetailsController" as CTRL
participant "Repositories" as REPOS
participant "repositories \n :Repositories" as REPO_SINGLETON
participant "scenarioRepository \n :ScenarioRepository" as SCEN_REPOS
participant ":ScenarioListMapper" as SMAPPER
participant ":List<Scenario>" as LIST_SCENARIO
participant ":List<ScenarioDTO>" as SLDTO
participant ":ScenarioDTO" as SDTO
participant "stationRepository \n :StationRepository" as STATION_REPOS
participant ":StationListMapper" as STATIONMAPPER
participant ":List<Station>" as LIST_STATION
participant ":List<StationDTO>" as STATIONLDTO
participant ":StationDTO" as STATIONDTO
participant "station \n :Station" as STATION


activate PLAYER

    PLAYER -> UI : asks to see stations
    activate UI

        UI --> CTRL** : create()

            UI -> CTRL : getAvailableScenarioNames()
           activate CTRL

                       CTRL -> REPOS : getInstance()
                       activate REPOS

                       REPOS --> CTRL : repositories
                       deactivate REPOS

                       CTRL -> REPO_SINGLETON : getScenarioRepository()
                       activate REPO_SINGLETON
                       REPO_SINGLETON --> CTRL : scenarioRepository
                       deactivate REPO_SINGLETON

                       CTRL -> SCEN_REPOS : getScenarios()
                       activate SCEN_REPOS
                       SCEN_REPOS --> CTRL : scenarioList
                       deactivate SCEN_REPOS

                       CTRL -> SMAPPER : toDTO(scenarioList)
                       activate SMAPPER

                       SMAPPER --> SLDTO** : create()

                       loop for each scenario
                           SMAPPER -> LIST_SCENARIO : getScenario()
                           activate LIST_SCENARIO
                           LIST_SCENARIO --> SMAPPER : scenario
                           deactivate LIST_SCENARIO

                           SMAPPER -> SMAPPER : toDTO(scenario)
                           activate SMAPPER

                           SMAPPER --> SDTO** : create(map, year, locomotiveTypes, importation, exportation, changer)
                           deactivate SMAPPER

                           SMAPPER -> SLDTO : addScenario(scenario)
                           activate SLDTO
                           deactivate SLDTO
                       end loop

                       SMAPPER --> CTRL : scenarioListDTO
                       deactivate SMAPPER

                       CTRL -> SLDTO : getAvailableScenarioNames(scenarioListDTO)
                       activate SLDTO

                       SLDTO --> CTRL : scenario names
                       deactivate SLDTO

                       CTRL --> UI : scenario names
           deactivate CTRL

           UI --> PLAYER : shows the list of scenarios
        deactivate UI

            PLAYER -> UI : selects a scenario
        activate UI

            UI -> CTRL : getAvailableStationNames()
                 activate CTRL

                                      CTRL -> REPOS : getInstance()
                                      activate REPOS

                                      REPOS --> CTRL : repositories
                                      deactivate REPOS

                                      CTRL -> REPO_SINGLETON : getStationRepository()
                                      activate REPO_SINGLETON
                                      REPO_SINGLETON --> CTRL : stationRepository
                                      deactivate REPO_SINGLETON

                                      CTRL -> STATION_REPOS : getStations()
                                      activate STATION_REPOS
                                      STATION_REPOS --> CTRL : stationList
                                      deactivate STATION_REPOS

                                      CTRL -> STATIONMAPPER : toDTO(stationList)
                                      activate STATIONMAPPER

                                      STATIONMAPPER --> STATIONLDTO** : create()

                                      loop for each station
                                          STATIONMAPPER -> LIST_STATION : getStation()
                                          activate LIST_STATION
                                          LIST_STATION --> STATIONMAPPER : station
                                          deactivate LIST_STATION

                                          STATIONMAPPER -> STATIONMAPPER : toDTO(station)
                                          activate STATIONMAPPER

                                          STATIONMAPPER --> STATIONDTO** : create(stationType, position, name, center, demandedCargo, suppliedCargo)
                                          deactivate STATIONMAPPER

                                          STATIONMAPPER -> STATIONLDTO : addStation(stationDTO)
                                          activate STATIONLDTO
                                          deactivate STATIONLDTO
                                      end loop

                                      STATIONMAPPER --> CTRL : stationListDTO
                                      deactivate STATIONMAPPER

                                      CTRL -> STATIONLDTO : getAvailableStationNames(stationListDTO)
                                      activate STATIONLDTO

                                      STATIONLDTO --> CTRL : station names
                                      deactivate STATIONLDTO

                                      CTRL --> UI : station names
                 deactivate CTRL

                UI --> PLAYER : shows the list of stations
        deactivate UI

    PLAYER -> UI : selects a station
        activate UI

        UI -> CTRL : getBuildingDetailsString(stationIndex)
        activate CTRL

        STATION --> CTRL: buildingDetails
        deactivate STATION

               CTRL --> UI : buildingDetails
        deactivate CTRL

               UI -> CTRL : getCargoInfo(stationIndex)
        activate CTRL

        CTRL -> STATION: getCargoInfo(index)
                activate STATION

                STATION --> CTRL: cargoInfo
                deactivate STATION

                CTRL --> UI : cargoInfo
        deactivate CTRL

        UI --> PLAYER : shows station details
    deactivate UI

deactivate PLAYER
@enduml