@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

left to right direction

hide circle
hide methods


class Editor {
    name
    password
}

class Map {
    size
    name
    scale
}


Editor "1" -- "*" Map: creates >
@enduml