@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Player" as PLAYER
participant ":BuyLocomotiveUI" as UI
participant ":BuyLocomotiveController" as CTRL
participant "Repositories" as REPOS
participant "repositories \n :Repositories" as REPO_SINGLETON
participant "scenarioRepository \n :ScenarioRepository" as SCEN_REPOS
participant ":ScenarioListMapper" as SMAPPER
participant ":List<Scenario>" as LIST_SCENARIO
participant ":List<ScenarioDTO>" as SLDTO
participant ":ScenarioDTO" as SDTO
participant "scenario \n :Scenario" as SCENARIO
participant "locomotiveModelRepository \n :LocomotiveModelRepository" as LMODEL_REPOS
participant ":LocomotiveModelListMapper" as LMODELMAPPER
participant ":List<LocomotiveModel>" as LIST_LMODEL
participant ":List<LocomotiveModelDTO>" as LMODELLDTO
participant ":LocomotiveModelDTO" as LMODELDTO
participant "locomotiveRepository \n :locomotiveRepository" as LOCO_REPOS
participant ":LocomotiveMapper" as LMAPPER
participant ":LocomotiveDTO" as LDTO
participant "locomotive \n :Locomotive" as LOCOMOTIVE

activate PLAYER

    PLAYER -> UI : asks for the list of locomotives
    activate UI
        UI --> CTRL** : create()

                    UI -> CTRL : getAvailableScenarioNames()
                   activate CTRL

                               CTRL -> REPOS : getInstance()
                               activate REPOS

                               REPOS --> CTRL : repositories
                               deactivate REPOS

                               CTRL -> REPO_SINGLETON : getScenarioRepository()
                               activate REPO_SINGLETON
                               REPO_SINGLETON --> CTRL : scenarioRepository
                               deactivate REPO_SINGLETON

                               CTRL -> SCEN_REPOS : getScenarios()
                               activate SCEN_REPOS
                               SCEN_REPOS --> CTRL : scenarioList
                               deactivate SCEN_REPOS

                               CTRL -> SMAPPER : toDTO(scenarioList)
                               activate SMAPPER

                               SMAPPER --> SLDTO** : create()

                               loop for each scenario
                                   SMAPPER -> LIST_SCENARIO : getScenario()
                                   activate LIST_SCENARIO
                                   LIST_SCENARIO --> SMAPPER : scenario
                                   deactivate LIST_SCENARIO

                                   SMAPPER -> SMAPPER : toDTO(scenario)
                                   activate SMAPPER

                                   SMAPPER --> SDTO** : create(map, year, locomotiveTypes, importation, exportation, changer)
                                   deactivate SMAPPER

                                   SMAPPER -> SLDTO : addScenario(scenario)
                                   activate SLDTO
                                   deactivate SLDTO
                               end loop

                               SMAPPER --> CTRL : scenarioListDTO
                               deactivate SMAPPER

                               CTRL -> SLDTO : getAvailableScenarioNames(scenarioListDTO)
                               activate SLDTO

                               SLDTO --> CTRL : scenario names
                               deactivate SLDTO

                               CTRL --> UI : scenario names
                   deactivate CTRL

        UI --> PLAYER : shows available scenarios
    deactivate UI

PLAYER -> UI : selects scenario
activate UI

    UI -> CTRL : getAvailableLocomotiveModelDescriptions()
        activate CTRL

                  CTRL -> REPOS : getInstance()
                  activate REPOS

                  REPOS --> CTRL : repositories
                  deactivate REPOS

                  CTRL -> REPO_SINGLETON : getLocomotiveModelRepository()
                  activate REPO_SINGLETON
                  REPO_SINGLETON --> CTRL : locomotiveModelRepository
                  deactivate REPO_SINGLETON

                  CTRL -> LMODEL_REPOS : getLocomotiveModels()
                  activate LMODEL_REPOS
                  LMODEL_REPOS --> CTRL : locomotiveModelList
                  deactivate LMODEL_REPOS

                  CTRL -> LMODELMAPPER : toDTO(locomotiveModelList)
                  activate LMODELMAPPER

                  LMODELMAPPER --> LMODELLDTO** : create()

                  loop for each locomotiveModel
                      LMODELMAPPER -> LIST_LMODEL : getLocomotiveModel()
                      activate LIST_LMODEL
                      LIST_LMODEL --> LMODELMAPPER : locomotiveModel
                      deactivate LIST_LMODEL

                      LMODELMAPPER -> LMODELMAPPER : toDTO(locomotiveModel)
                      activate LMODELMAPPER

                      LMODELMAPPER --> LMODELDTO** : create()
                      deactivate LMODELMAPPER

                      LMODELMAPPER -> LMODELLDTO : addLocomotiveModel(locomotiveModelDTO)
                      activate LMODELLDTO
                      deactivate LMODELLDTO
                  end loop

                  LMODELMAPPER --> CTRL : locomotiveModelListDTO
                  deactivate LMODELMAPPER

                  CTRL -> LMODELLDTO : getAvailableLocomotiveModelDescriptions(locomotiveModelListDTO)
                  activate LMODELLDTO

                  LMODELLDTO --> CTRL : locomotiveModel descriptions
                  deactivate LMODELLDTO

                  CTRL --> UI : locomotiveModel descriptions
                  deactivate CTRL

    UI --> PLAYER : shows the list of locomotive models descriptions
deactivate UI

PLAYER -> UI : selects a locomotive model
activate UI

    UI -> CTRL : createLocomotive(dto, scenarioIndex)
    activate CTRL

   CTRL -> REPOS : getInstance()
       activate REPOS

           REPOS --> CTRL : repositories
       deactivate REPOS

       CTRL -> REPO_SINGLETON : getLocomotiveRepository()
       activate REPO_SINGLETON
       REPO_SINGLETON --> CTRL: locomotiveRepository
       deactivate REPO_SINGLETON
       CTRL -> LOCO_REPOS: createLocomotive(dto)
       activate LOCO_REPOS

       LOCO_REPOS -> LMAPPER : toLocomotive(dto)
       activate LMAPPER

       LMAPPER -> LDTO: getLocomotiveModel()
       activate LDTO

       LDTO --> LMAPPER: locomotiveModel
       deactivate LDTO

       LMAPPER --> LOCO_REPOS: locomotiveModel
       deactivate LMAPPER

       LOCO_REPOS -> LOCO_REPOS: nextId()
       activate LOCO_REPOS

       LOCO_REPOS --> LOCO_REPOS: iD
       deactivate LOCO_REPOS

       LOCO_REPOS -> LOCOMOTIVE: createLocomotive(locomotiveModel, iD)
       activate LOCOMOTIVE

       LOCOMOTIVE -> LOCOMOTIVE: checkModel(model)
           activate LOCOMOTIVE

           LOCOMOTIVE --> LOCOMOTIVE: valid
           deactivate LOCOMOTIVE

       LOCOMOTIVE -> LOCOMOTIVE: checkId(iD)
       activate LOCOMOTIVE

       LOCOMOTIVE --> LOCOMOTIVE: valid
       deactivate LOCOMOTIVE

       LOCOMOTIVE --> LOCO_REPOS: locomotive
       deactivate LOCOMOTIVE

       LOCO_REPOS -> LOCO_REPOS: addLocomotive(locomotive)
       activate LOCO_REPOS

       LOCO_REPOS --> LOCO_REPOS: success
       deactivate LOCO_REPOS

        LOCO_REPOS -> SCENARIO: locomotive
        deactivate LOCO_REPOS

        activate SCENARIO

           SCENARIO -> SCENARIO: addLocomotive(locomotive)
           activate SCENARIO

           SCENARIO --> SCENARIO: success
           deactivate SCENARIO

           SCENARIO --> CTRL: success
           deactivate SCENARIO

       CTRL --> UI: success
    deactivate CTRL

    UI --> PLAYER : displays operation success
deactivate UI

deactivate PLAYER

@enduml