@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Employee
participant "System" as System

activate Employee

    Employee -> System : asks to assign a train to a route
    activate System

    System --> Employee : shows the list of available scenarios
    deactivate

    Employee -> System : selects a scenario
    activate System

        System --> Employee : shows available locomotives for the assignment
    deactivate System

    Employee -> System : selects a locomotive
    activate System

    System --> Employee : shows existing stations
    deactivate System

    Employee -> System : selects a station to add as the beginning one
    activate System

    System --> Employee : shows existing stations
    deactivate System

    Employee -> System : selects a station to add as the ending one
    activate System

    loop for each PointOfRoute

    System --> Employee : shows remaining existing stations
    deactivate System

    Employee -> System : selects a station to add as a PointOfRoute to the route
    activate System

    System --> Employee: shows the available cargo to be picked up
    deactivate System

    Employee -> System: selects the wanted cargo to be picked up
    activate System

    System --> Employee: shows the available cargo modes
    deactivate System

    Employee -> System: selects the wanted cargo mode
    activate System

    end loop

    System --> Employee: shows all data for confirmation
    deactivate System

    Employee -> System : confirms all data
    activate System

    System --> Employee : creates the route and displays success
    deactivate System
@enduml
