@startuml

left to right direction

actor Editor
actor Player

usecase "US001 - Create a Map" as US001
usecase "US002 - Place an Industry" as US002
usecase "US003 - Add a City" as US003
usecase "US004 - Create a Scenario" as US004
usecase "US005 - Build a Station" as US005
usecase "US006 - Upgrade a Station" as US006
usecase "US007 - View Station Details" as US007
usecase "US008 - Build a Railway" as US008
usecase "US009 - Buy a Locomotive" as US009
usecase "US010 - Route Selection" as US010
usecase "US011 - List all Trains" as US011
usecase "US012 - Simulate Cargo Generation" as US012
usecase "US013 - Train Travel Verification" as US013
usecase "US014 - Railway Lines Maintenance" as US014
usecase "US015 - Profit Statistical Analysis" as US015
usecase "US016 - Station Comparative Analysis" as US016
usecase "US017 - Cargo Analysis" as US017
usecase "US018 - Train Distribution Analysis" as US018
usecase "US019 - Save a Map" as US019
usecase "US020 - Load a Map" as US020
usecase "US021 - Save a Scenario" as US021
usecase "US022 - Load a Scenario" as US022
usecase "US023 - Save a Simulation" as US023
usecase "US024 - Load a Simulation" as US024
usecase "US025 - Year Financial Results" as US025
usecase "US026 - US013/14 Algorithm Efficiency" as US026
usecase "US027 - Shortest Routes Between Stations" as US027
usecase "US028 - US027 Procedure Efficiency" as US028
usecase "US029 - Variable-Sized Inputs Tests" as US029
usecase "US030 - Best-Fitting Curve Obtention" as US030
usecase "US031 - Revenue Statistical Analysis" as US031

Editor -- US001
Editor -- US002
Editor -- US003
Editor -- US004
Editor -- US019
Editor -- US020
Editor -- US021
Editor -- US022

Player -- US005
Player -- US006
Player -- US007
Player -- US008
Player -- US009
Player -- US010
Player -- US011
Player -- US012
Player -- US013
Player -- US014
Player -- US015
Player -- US016
Player -- US017
Player -- US018
Player -- US023
Player -- US024
Player -- US025
Player -- US026
Player -- US028
Player -- US029
Player -- US027
Player -- US030
Player -- US031


@enduml

@enduml